services:
  # Front-end and Nginx Web Server
  client:
    build: ./client
    container_name: mern-client
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
    depends_on:
      server:
        condition: service_healthy
    networks:
      - mern-network

  # Back-end API
  server:
    build: ./server
    container_name: mern-server
    restart: always
    environment:
      - MONGO_URI=mongodb://mern-mongodb:27017/mern-database
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - mern-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MongoDB database
  mongodb:
    image: mongo:latest
    container_name: mern-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Mongo Express GUI
  mongo-express:
    image: mongo-express:latest
    container_name: mern-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mern-mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mern-network

# Shared Docker network
networks:
  mern-network:
    driver: bridge

# Persistent volume for MongoDB
volumes:
  mongodb_data:
